name: GH Actions CI
on:
  workflow_dispatch:

concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}


jobs:
  collect-stats:
    name: Collect stats
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Build information
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Set up micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yaml

    - name: Python information
      run: |
        which python
        python --version
        conda list

    - name: Run data collection
      run: openff-stats run-all

    - name: Deploy data to main
      if: github.event_name != 'pull_request'
      env:
        GH_USER: github-actions
        GH_EMAIL: "github-action@users.noreply.github.com"
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPOSITORY: "github.com/${{ github.repository }}.git"
      run: |
        BRANCH="${GITHUB_REF#refs/heads/}"

        git config user.name $GH_USER
        git config user.email $GH_EMAIL
        git remote set-url origin "https://${GH_USER}:${GH_TOKEN}@${GH_REPOSITORY}"

        sed -i "s/^Date last updated: .*/Date last updated: $(date -u +%Y-%m-%d)/" README.md

        git add -A data README.md
        git diff-index --quiet HEAD -- || git commit -m "Update stats data [skip ci]"
        git push origin HEAD:main
